### ISSUE TITLE
Doesn't work for second variable in a declaration

### ISSUE THREAD

**Issue by madeleineostoja** [willofindie/vscode-cssvar#11]
The extension doesn't provide intellisense autocomplete if using a second variable in a CSS rule, eg:

```css
padding: var(--size-4) var(--size-7);
```

Autocomplete works when writing the first variable (`--size-4`), but nothing pops up when writing the second variable (`--size-7`).

Using CSS-in-JS in `.tsx` files if it matters.

**Comment by phoenisx** [comment]
Apologies! I was away last few weeks. Also, I might not be available for a month or 2.

Anyways, will take a look, whenever I get time.

Thanks for opening the issue 🙇
