### ISSUE TITLE
[Bug] Failed to parse CSS variable with @layer declaration

### ISSUE THREAD

**Issue by jasonchrista** [willofindie/vscode-cssvar#110]
**Describe the bug**
When my file starts with `@layer tokens, reset, components;`, every time I save that file I get the message Failed to parse CSS variable is files: index.css

**To Reproduce**
1.  Add a new CSS file
2. Start file with a @layer definition
3. Save

**Expected behavior**
@layer is valid CSS, no error should be present.

**Comment by phoenisx** [comment]
Thanks for reporting this.
I'll fix this in the next patch release 👍🏽
