### ISSUE TITLE
Doesn't work with styled-components typescript

### ISSUE THREAD

**Issue by fernandolucchesi** [willofindie/vscode-cssvar#14]
Hi, I can't make this work with styled-components and typescript. I tried solution from #9 but no success.

My use case:
```
const StyledTime = styled.div`
  margin-top: var(--space-medium);
  margin-bottom: var(--space-xSmall);
  color: var(--moss-green-100);
  font-weight: var(--fontWeight-light);
`
```

Current settings:
```
"cssvar.files": [ "./web/styles/settings.ts"],
"cssvar.extensions": ["typescript", "typescriptreact", "tsx", "ts", "css", "less"],
```

**Comment by phoenisx** [comment]
Hi @fernandolucchesi , can u share a Codesandbox link that I can reuse to validate the bug (if any)?

Or let me the versions of Modules being used and a Styled-Component snippet, that isn't working for you!!.

**Comment by phoenisx** [comment]
@fernandolucchesi Closing this issue, as I am not able to replicate.
Please reopen if the issue still persists.

Providing a small reproduction of the issue would help!!

**Comment by phoenisx** [comment]
Support for universal parsing will be added as part of #27, as part of v2.0 release
