### ISSUE TITLE
Enable to extension for postcss files

### ISSUE THREAD

**Issue by MangelMaxime** [willofindie/vscode-cssvar#15]
Hello,

VSCode has a  [postcss-language](https://github.com/csstools/postcss-language) extension.

This extension add support for some `@` rules like `@import-glob` which avoid having a warning in the file.

I tried to make the extension works for `postcss` language by adding `onLanguage:postcss` but it doesn't seems to be enough.

Do you know if there is another places that need to be updated for the extension to work with `postcss` files?

Edit: Of course, my question is only valid if you are ok to support that language activation :)

**Comment by phoenisx** [comment]
Hi @MangelMaxime

I won't directly add support for CSS variants, like Sass or Postcss, etc., but I do plan to add support for **Postcss plugins**, which will help to enable addon features not supported by this extension.

_Details for this can be tracked here: #12_ 

Let me know if that's what you want as well, we can close this issue and track it in one place #12

**Comment by MangelMaxime** [comment]
The difference between my issue and the workaround/explanation done in #12 is that the file extension is `*.css` but the language ID associated to the file is `postcss`.

Which means the extension doesn't seems to register the ItemCompletionProvider to it.

**Comment by phoenisx** [comment]
Cool!!

Thanks for the details @MangelMaxime. I will enable support for that extension as well, but full support will be available only once #12 is fixed. 🎉

**Comment by phoenisx** [comment]
Hi @MangelMaxime 

I have never used postcss extensions before, so need some guidance understanding your requirements.

As per VSCode docs, there is no direct support for `postcss` extensions, details can be read [here](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers).

`.pcss` and `.postcss` extension support is provided by the VSCode extension https://marketplace.visualstudio.com/items?itemName=csstools.postcss and not by default.

Since `cssvar` extension only supports vanilla CSS, thus something like https://stackoverflow.com/a/50042886/2849127 should be a better option (in my opinion).

**_Let me know, if above solution works for you!!_**

**Comment by MangelMaxime** [comment]
Hello @phoenisx,

I was using this extension https://github.com/csstools/postcss-language to add support for PostCSS.

https://github.com/csstools/postcss-language register by default to `.css` files. I needed to use that extension because otherwise, when using future CSS syntax like nesting, etc. I would have error all over the CSS files making it an unpleasant experience.

So by using https://github.com/csstools/postcss-language, I didn't have to setup the `files.associations` property. 

I believe that https://github.com/csstools/postcss-language change the [language id for `.css` files](https://github.com/csstools/postcss-language/blob/master/package.json#L26-L39) and so I tried to do

```json
`"files.associations": {
   "*.css": "css"
}
```

to allow your extension to show up but it didn't work at the time.

If you want, I can try to set up a minimal reproduction repository, so you can see what I was doing?

**Comment by phoenisx** [comment]
Do make sure the CSS used inside files mentioned in `cssvar.files` are pure CSS, supported by CSS3 Spec and default postcss parser without any plugin.

Anyways, minimal repro would be really helpful @MangelMaxime.

**Comment by MangelMaxime** [comment]
Hello @phoenisx ,

sorry for the late replay I was busy with others stuff at work.

Here is a reproduction repository: https://github.com/MangelMaxime/willofindie-vscode-cssvar-issues-15-

I have your extensions installed and this extension too https://marketplace.visualstudio.com/items?itemName=csstools.postcss

By default, the `postcss` takes over the `.css` files and provides support for the new syntax added via postcss plugins.

This avoid having error or warning everywhere in the file:

![image](https://user-images.githubusercontent.com/4760796/147205422-c0b486c5-5ce4-4756-8e7e-9cc0105e1bba.png)

See how `@import-glob` is having a warning when I set the file as a CSS file.

However, when the file is configure as a `PostCSS` file, your extension doesn't trigger on autocomplete this was what I was trying to fix by opening this issue.

**Comment by phoenisx** [comment]
This is fixed now!

Thanks for your support @MangelMaxime
