### ISSUE TITLE
Can't get it to work with svelte

### ISSUE THREAD

**Issue by brandonFaf** [willofindie/vscode-cssvar#17]
Hello,
I'm trying to use [Open Props](https://open-props.style/) in my sveletekit project and this extension is recommended in the the docs of Open Props to get easy IntelliSense. The extension looks awesome and I've gotten it to work with a css file so i know how great it is. 

Not sure how much work it would take to work with Svelte but I would love to be able to use it in my project. 

I'll try to look at the code to contribute, but I haven't done an extension before so there is a little ramping up. 

Thanks for the great work.

**Comment by phoenisx** [comment]
Thanks for your support.
I have fixed and added support for `svelte` and `vue` js both.

**Comment by phoenisx** [comment]
If you would like to contribute, you can take a look here: https://github.com/willofindie/vscode-cssvar/issues/1, and what features I want to integrate to reach `v1`

**Comment by brandonFaf** [comment]
Thank you so much! Works like a charm!
