### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by BazukenDev** [willofindie/vscode-cssvar#2]
Looks simple, but didn't work. Watch screenshot.
![cssvardidntwork](https://user-images.githubusercontent.com/61555073/113869327-40fd0600-97b9-11eb-8818-9dafb1bc57af.jpg)

**Comment by phoenisx** [comment]
`cssvar.files` is relative to project root directory, or you can provide an absolute path.

I think it should be `src/default/variables.scss`, instead of `variables.scss`

Let me know if this fixes your issue.

**Comment by phoenisx** [comment]
Also, I would recommend you to define `cssvar.files` setting in your `.vscode` Project Settings, instead of defining it in your Global `settings.json` file, since each project might have different location to your default css variables file.

**Comment by BazukenDev** [comment]
Yes. You right. 
`    "cssvar.files": ["src/default/variables.scss"]`
- solve this misunderstanding. 

Option like this may by more useful: "**/variables.scss".

But wat about project like one of mine? It has multiple apps in one repository. 

apps/www/
   p1/src/vars.scss
   p1/src/page.scss

   p2/src/vars.scss
   p2/src/page.scss

So is it possible to use it like this? One workspace, one options file, but in 
_'p1/src/page.scss'_ I well see vars from _'p1/src/page.scss'_
and in 
_'p2/src/page.scss'_ I well see vars from _'p2/src/page.scss'_?

**Comment by phoenisx** [comment]
I can support something like `**/variables.scss`, but issue with such a logic is that, it can load all `**/variables.scss` files in a project, irrespective of it being a css variable file or not. This could make the plugin slow.

_Also, let me know if I misunderstood you:_

- You have two projects - `p1` and `p2` under root directory `apps/www/`.
- In your VSCode you normally open `apps/www/` root in whole, or do you open `apps/www/p1` and `apps/www/p2` separately??
- In case you have `apps/www/` root project open, you can define 2 `cssvar.files`, eg.:
  - `cssvar.files: ["p1/src/vars.scss", "p2/src/vars.scss"]` 
  - This will load both the files in unison. The only issue with above approach is any duplicate variable
     from `apps/www/p1/src/vars.scss` will be overridden by `apps/www/p2/src/vars.scss`

About your last query:
> So is it possible to use it like this? One workspace, one options file, but in
> 'p1/src/page.scss' I well see vars from 'p1/src/page.scss'
> and in
> 'p2/src/page.scss' I well see vars from 'p2/src/page.scss'?

- You can open`apps/www/p1` and `apps/www/p2` separately, as different projects in VSCode.
  - Defining `cssvar.files: ["src/p1-vars.scss", "src/p1-vars2.scss"]` for `apps/www/p1` project, will work
  - Defining `cssvar.files: ["src/p2-vars.scss", "src/p2-vars2.scss"]` for `apps/www/p2` project, will work

You can also define absolute paths, if needed:
- Like `cssvar.files: ["/home/{user}/apps/www/p1/src/vars.scss"]` for `apps/www/p1` project

Will update my documentation accordingly 👍🏾 

**P.S.:** Also, I think supporting variables directory instead would help you out, for eg. `"cssvar.dirs": ["src/variables"]`
The only issue is, the project will become a little complicated, if project supports both `.css` and `.scss` variable
files in such directories. I wanted to keep project simple, and thus used `files` instead as
normally people tend to keep 1-2 css variable files or max 3-4 files in a project.

**Comment by BazukenDev** [comment]
You right, mixing all variables from all vars files not good at all. Hard to do it simple and universal at same time. 

I made a mistake here: 

> About your last query:
> 
> So is it possible to use it like this? One workspace, one options file, but in
> 'p1/src/page.scss' I well see vars from 'p1/src/page.scss'
> and in
> 'p2/src/page.scss' I well see vars from 'p2/src/page.scss'?

It mast look this way:

> 'p1/src/page.scss' I well see vars from 'p1/src/vars.scss'
> and in
> 'p2/src/page.scss' I well see vars from 'p2/src/vars.scss'?

And yes, I opened only one vscode window for this two projects (p1 and p2). Let say both of them is under one git pero.

![2 rootvars](https://user-images.githubusercontent.com/61555073/114370168-d4eb1b00-9b87-11eb-9195-e4aefaa88649.jpg)

**Comment by phoenisx** [comment]
In your case, I would suggest to got with
`cssvar.files: ["www/p1/src/vars.scss", "www/p2/src/vars.scss"]`

This will load both the files in unison. Though, similar named variables from `csstext/www/p1/src/vars.scss` will be overridden by `csstext/www/p2/src/vars.scss`

---

**P.S.** Opening, project `p1` separately in VSCode, and setting `cssvar.files` accordingly, would be a better approach

**Comment by phoenisx** [comment]
_Closing this PR in support for the above mentioned details._
 
Please feel free to open a different PR, if the issue isn't resolved.

**Comment by phoenisx** [comment]
Have added support for Glob patterns as part of release 0.0.7, as more people are requesting this change - #4
