### ISSUE TITLE
TypeScript and styled-components

### ISSUE THREAD

**Issue by melkerydman** [willofindie/vscode-cssvar#27]
Heya, 

I've been spending more time than I'd like to admit getting the extension working with TS and styled-components, without success. Maybe what I'm trying to achieve is not possible, otherwise I'd love to hear what I'm doing wrong.

The issue I'm getting is "Failed to parse CSS variables in files" .

This is the config:
`"cssvar.extensions": ["ts", "tsx"],`
`
"cssvar.files": ["src/Styles/Global.ts"]
`

This is how I'm declaring the variables in Global.ts
```
import { createGlobalStyle } from "styled-components";

export default createGlobalStyle`
:root {
  --h1: 44px;
  --h2: 32px;
  --h3: 24px;
}
`
```

I've done some troubleshooting getting it working with css, so the issue lies with the styled-components and typescript, is there a potential solution to this?

Really cool extension and thanks in advance🤗

**Comment by phoenisx** [comment]
Thanks for your support.

`JSX?/TSX?` parsing is not supported yet. Please take look at this Doc: [Customizing the Extension](]https://github.com/willofindie/vscode-cssvar/blob/master/customize-extension.md).

I can still provide support for JSX? parsing using [postcss-jsx](https://github.com/gucong3000/postcss-jsx) but will have to thoroughly test it.

You can get IntelliSense in JS like files, but parsing such files would be too broad for this extension. 😅 

Let me think of some solutions for this and see if they are feasible.

**Comment by melkerydman** [comment]
I fully understand, thanks for getting back so quickly.

All the best and keep up the good work 😁

**Comment by phoenisx** [comment]
Thanks for opening this ticket.

I am planning to add minimal support for all js like files, with minimal parsing. Let's see how that works out.
This feature can be buggy, so will keep this behind a config toggle.

Since I won't be available this week, I will most probably work on this next weekend 👍🏾 

I am hoping to release it as part of the 1.5

**Comment by phoenisx** [comment]
Hi

This feature has been added to the extension in `v2.0.0`. 🎉 

_Please do test it out, and let me know if you find any bugs or have any suggestions for improvements._ 🙇🏽 


> Support is limited to parse Template Literals only, and not JS Objects (as it's out of scope for this project), which anyways adds support for `styled-components`.
