### ISSUE TITLE
extension not working at all - how to solve it?

### ISSUE THREAD

**Issue by lucianahanan** [willofindie/vscode-cssvar#31]
I have a simple styled component file, where I tried to see the extension in action. But when typing var(-- ,  nothing happens from the extension, none of the vars shows in the popup list, no color next to existing vars typed, nada. It was a .ts file.

Also tried on a .css file, with plain css, and it's the same, nothing happens from the extension.

Tried to close VS code, reinstall extension, but still no go. Ideas ?

**Comment by phoenisx** [comment]
I plan to add examples in the future and remove dependency on the `files` config.

Can you share your `.vscode/settings.json` file? It will help me figure out what config you have used wrong.

**Comment by lucianahanan** [comment]
I couldn't find a way to export vscode settings. But it's configured like default instalation of it. If you have any discord server, I can share my screen on realtime.

**Comment by phoenisx** [comment]
I have added a very basic example with pure CSS setup here: https://github.com/willofindie/vscode-cssvar/tree/master/examples/basics

Please validate your configs from the mentioned example's `.vscode/settings.json`.

Do make sure:

- A local config is created for the project you are working on
- `cssvar.files` has a proper regex to find files to parse CSS variables from
- `cssvar.extensions`, to contain a proper list of extensions you want the intellisense to be enabled for.

Details for the above config are mentioned in this Projects [README.md](https://github.com/willofindie/vscode-cssvar/blob/master/README.md) file.

**Comment by lucianahanan** [comment]
The instructions are not very clear. The extension will not work out of the box?

Can I add these json settings that will work for every project opened by vscode, without having to add a setting file for each new one? If so, where can I save them and how does the setting files should look like to accept all file extensions possible?
