### ISSUE TITLE
The extension does not work

### ISSUE THREAD

**Issue by SineYlo** [willofindie/vscode-cssvar#33]
Hi!
I installed the extension, and it didn't work right away, I went to the settings to specify the path to the files, and it still doesn't work. I am more than sure that I am doing something wrong, but there is not much instruction on how to run this extension. Furthermore, I attach screenshots and an explanation of what I did.

1. Here is my project folder. I write all the code in the `styles.scss` file. The `styles.css` file is the final file into which all SCSS files merge. The `variables.scss` file contains the very variables that I plan to call.
![picture-1](https://i.ibb.co/mzgKZPZ/Code-i-Jr6wy-Df-GZ.png)
2. Here are the contents of the `variables.scss` file.
![picture-2](https://i.ibb.co/BGZsZ3h/Code-G8m-Ru6k-Tl-Y.png)
3. And actually here is the main `styles.scss` file in it, I'm trying to call a variable and there are absolutely no hints. As if he just doesn't see this variable :(. Actually, it was exactly the same before installing this extension. Nothing changed after that.
![picture-3](https://i.ibb.co/prBrjmH/Code-d-No2-WTve5e.png)
---
In `settings.json` I didn't prescribe anything.
I honestly don't know what the problem is. Therefore, I hope you can tell me how to make this extension work.
Maybe I didn't understand the meaning of this extension, but it seems to me that it just doesn't work for me :)

**Comment by phoenisx** [comment]
This extension does not support Sass parsing by default, to keep the extension size small and concise.

Scss is a custom CSS extension, did you try the methods mentioned [in Custom Extension](https://github.com/willofindie/vscode-cssvar/blob/master/customize-extension.md) to support Sass files?

Let me know if that works out for you.

**Comment by SineYlo** [comment]
@phoenisx 
Either I'm doing something wrong or it still doesn't work with SCSS...

1. I have installed 2 packages as stated in the instructions.
![picture-1](https://i.ibb.co/YXM70Mx/Code-Mf30ai1-Jor.png)
2. In `settings.json` has prescribed some settings, which are also specified in the instructions. (in the path to the variable files, I specifically specified all the SCSS files so as not to mess up somewhere).
![picture-2](https://i.ibb.co/GM4zwgw/Code-pp-QYHuo-Cj-K.png)
3. I also tried to create a postcss config, but nothing has changed.

Maybe I wrote something wrong?
I'm more than sure I'm doing something wrong.

**Comment by SineYlo** [comment]
@phoenisx 
There has been a little progress and at least there is such an error:
![picture-1](https://i.ibb.co/XJ1p7Mz/Code-Z0-YL8da-Sw-G.png)
It is not clear why it occurs because I installed postcss (if anything, I installed this package in `devDependencies`)
It seems to me that if we can fix this error, then everything will work :D

**Comment by SineYlo** [comment]
@phoenisx 
In general, I figured out what needs to be done to make it all work for SCSS files
1. You need to go to `settings.json` and register the following settings (I have written in the parameter `cssvar.files` selection of all SCSS files for convenience):
![picture-1](https://i.ibb.co/gRRsR4M/Code-Lw-NFn6-Qf-Oa.png)
2. You need to install the `postcss` and `postcss-scss` packages (used this command — `npm i -D postcss postcss-scss`)
3. The last thing to do is restart `VS Code`

I suffered for a long time, but the result is worth it. 
If you wish, you can write this entire installation process somewhere in the README for use with SCSS files :)
I really liked this extension!
