### ISSUE TITLE
Publish extension on Open VSX

### ISSUE THREAD

**Issue by maiertech** [willofindie/vscode-cssvar#35]
Would you mind considering cross-publishing vscode-cssvar to https://open-vsx.org/?

I do most of my development on https://www.gitpod.io/ and from within their VS Code I do not have access to the VS Code marketplace, only Open VSX. 

You can find more information on how to publish your extension to Open VSX here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by maiertech** [comment]
Would it be ok if I open a PR in https://github.com/open-vsx/publish-extensions to get your extension to https://open-vsx.org/?

**Comment by phoenisx** [comment]
Sure!

I am not able to focus on this project for some time. Would love some support. Thanks! 🙇🏻‍♂️

**Comment by maiertech** [comment]
For reference: https://github.com/open-vsx/publish-extensions/issues/616.

**Comment by phoenisx** [comment]
Thanks for your help, will be closing this issue now 👍🏾

**Comment by maiertech** [comment]
If you ever want to take back control over publishing to Open VSX, check out the link in my first comment.

**Comment by phoenisx** [comment]
Hi I tried creating an account and a token to publish the latest version, but failed to do so.

How can I publish my extension to OVSX??

It's throwing me the following error:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/11786283/183251105-67e9edec-4d1d-4289-bc9c-16abd5fc593f.png">

I have followed all the steps from https://github.com/eclipse/openvsx/wiki/Publishing-Extensions and also created a PR to claim the namespace `phoenisx` here: https://github.com/EclipseFdn/open-vsx.org/issues/1160

**Comment by maiertech** [comment]
Not sure. You probably need to claim your name `phoenisx` back since @filiptronicek published your extension once before. I will ping him on Twitter.

**Comment by phoenisx** [comment]
No worries @maiertech!! Forgot to reply back here. [Claiming the phoenisx namespace](https://github.com/EclipseFdn/open-vsx.org/issues/1160) did the trick.

The above error doesn't show anymore!

Anyways, I couldn't publish the same version. So if I do face an issue publishing the new version, will ping you here. Thanks 🙇🏽
