### ISSUE TITLE
Breaks on css files when postcss language installed

### ISSUE THREAD

**Issue by madeleineostoja** [willofindie/vscode-cssvar#38]
If the PostCSS language support extension is installed (to allow postcss style syntax in `.css` files), this extension stops working in css files, but still works in other files.

**Comment by madeleineostoja** [comment]
Nevermind, I looked at the reviews of that language extension and it breaks a lot more than this plugin. I found out you can get 99% of what it gives you by just setting `css` files to `scss` in `file.associations` settings.

**Comment by phoenisx** [comment]
Hi @madeleineostoja!
Can you share which PostCSS extension caused this conflict? I want to keep a not of it in the [FAQs](https://github.com/willofindie/vscode-cssvar/issues/66). 🙇🏽
