### ISSUE TITLE
Color preview forwarding does not work for SCSS vars

### ISSUE THREAD

**Issue by GauBen** [willofindie/vscode-cssvar#39]
I use a mix of SCSS and CSS vars in order not to bloat my CSS files.

Here is what it looks like:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/48261497/178942642-ad3da6cc-bae1-4cb1-8be7-b3af33548493.png">

<img width="262" alt="image" src="https://user-images.githubusercontent.com/48261497/178942696-b2454802-ee1d-489e-a83a-a3673f2d025f.png">

As you can see, the color preview forwarding does work for bare variables which is [invalid syntax](https://sass-lang.com/documentation/breaking-changes/css-vars), but not for interpolated variables.

I would like the color preview to work for *simple* interpolations `#{$var}`. Reading #37 I understood you'd like not to embed a SCSS parser.

Thanks in advance.

**Comment by phoenisx** [comment]
Thanks for raising this issue.

Let me look into this 👍🏾

**Comment by phoenisx** [comment]
I've released `v1.4.1`. I hope it resolves your issue.

**Comment by GauBen** [comment]
Thanks for the quick fix!

<img width="979" alt="image" src="https://user-images.githubusercontent.com/48261497/179359815-19035958-152d-484a-88c8-7a4aefd11a5d.png">
