### ISSUE TITLE
Glob support

### ISSUE THREAD

**Issue by satche** [willofindie/vscode-cssvar#4]
It would be really usefull to have glob support for config propreties, especially `cssvar.files`

To clarify, we could go from
`cssvar.files: [ "css/foo.css", "css/bar.css" ]`
to
`cssvar.files: [ "css/**/*.css" ]`

**Comment by satche** [comment]
Thanks for the fix !

Glob work fine for paths, but not for files. To clarify:
`css/**/index.css` --> look for all the index.css files in directories
`css/**/*.css` --> don't match every files

I don't know if it's a possible behaviour ?

**Comment by phoenisx** [comment]
Can u share me your Directory structure and VSCode settings.json

I've tested this on my end, and it works for the following:

```sh
# Folder structure, where I have multiple files in single CSS directory
├── src
│  ├── App.css
│  ├── App.test.tsx
│  ├── App.tsx
│  ├── css-variables
│  │  ├── colors
│  │  │  ├── colors-blue.css
│  │  │  └── colors-red.css
│  │  └── spacing.scss
│  ├── index.css
```

My settings.json
```json
{
  "cssvar.files": ["src/css-variables/**/*.css", "src/css-variables/**/*.scss"],
  "cssvar.extensions": ["css", "scss", "ts", "tsx", "jsx"],
}
```

**Comment by phoenisx** [comment]
This could also happen due to CSS files not being pure CSS. Currently I am using [postcss](https://github.com/postcss/postcss) to parse CSS files, without any plugin to keep the extension size as small as possible.

Does any of your CSS files uses custom PostCSS modules or extensions, which might be the cause of this?

**Comment by phoenisx** [comment]
I release a fix, to handle Parsing errors. Hope this fixes your glob issue 👍🏾

**Comment by satche** [comment]
Yes it does, amazing ! Thank you for your job !
