### ISSUE TITLE
Support for astro extension

### ISSUE THREAD

**Issue by casderooij** [willofindie/vscode-cssvar#40]
Hi! I very much enjoy this extension but unfortunately there's no support for astro files yet. I tried adding the astro extension locally, tested it and works like a charm! I don't mind to create a PR :)

**Comment by phoenisx** [comment]
Thanks for your support!! 💯 

Can you check if the changes done to [fix this issue](https://github.com/willofindie/vscode-cssvar/issues/17), is what you are looking for as well?

If so, let me know. Or else if you would like to support, you can also raise a PR with `.astro` extension support 🙇🏾
Let me know

**Comment by casderooij** [comment]
Yes the changes are very similar to that issue. I created a PR: #42

**Comment by phoenisx** [comment]
Thanks for support @casderooij 🙇‍♂️

Closing this issue as it’s been resolved by your PR
