### ISSUE TITLE
`ignore` overrides explicit mentions of `node_modules` in `files` even when set to `[]`

### ISSUE THREAD

**Issue by kelvindecosta** [willofindie/vscode-cssvar#49]
The recent addition of the `ignore` option has caused a breaking change where `files` that point to `node_modules` are not accounted for.
Moreover, explicitly setting `ignore` to `[]` has no effect.

**Comment by kelvindecosta** [comment]
I think the problem lies with the underlying resolution of the default values.
In the [`package.json` settings for the extension metadata](https://github.com/willofindie/vscode-cssvar/blob/main/package.json#L69-L71), the default value for `ignore` is set to `[]` which is very odd considering the README says it is `[**/node_modules/**]`.

Furthermore, `getConfigValue` overwrites `[]`, explicitly set by the user, to the default value.

> Maybe it would be better to store the default values in the `package.json` metadata for the extension?

Thank you for actively maintaining this project.
It saves a lot of time.

**Comment by kelvindecosta** [comment]
I think the problem lies with the underlying resolution of the default values.
In the [`package.json` settings for the extension metadata](https://github.com/willofindie/vscode-cssvar/blob/main/package.json#L69-L71), the default value for `ignore` is set to `[]` which is very odd considering the README says it is `[**/node_modules/**]`.

Furthermore, `getConfigValue` overwrites `[]`, explicitly set by the user, to the default value.

> Maybe it would be better to store the default values in the `package.json` metadata for the extension?

Thank you for actively maintaining this project.
It saves a lot of time.

**Comment by phoenisx** [comment]
Hi @kelvindecosta 
Thanks for reporting this. Apologies for the inconvenience caused.

This happened due to managing 2 sources of default values 😅 
Since it couldn't be unit tested, it got released.

Anyways, I have understood the issue, will release a fix by tomorrow 👍🏾

**Comment by kelvindecosta** [comment]
Thank you for the quick response!

I've never experimented with writing VS Code plugins, so I'm not sure how complicated it can get to maintain them.

Thank you again for this project!

**Comment by kelvindecosta** [comment]
Thank you for the quick response!

I've never experimented with writing VS Code plugins, so I'm not sure how complicated it can get to maintain them.

Thank you again for this project!

**Comment by phoenisx** [comment]
This is fixed in `v1.7.1`.

Do let me know if you find any other bugs in this extension.

**Comment by kelvindecosta** [comment]
Works like a charm!
Thank you for the quick fix!
