### ISSUE TITLE
Problem - SCSS/CSS Using Variables in Media Queries

### ISSUE THREAD

**Issue by arekuki** [willofindie/vscode-cssvar#51]
Couldn't output Value and Definition due to Media Queries. 

See video screenshot. 

Can you fix it please.

https://user-images.githubusercontent.com/3696127/181593648-2f3fc263-cde1-47e0-8f1f-f5ef80ef8b0a.mp4

**Comment by phoenisx** [comment]
Since the parser doesn't evaluate CSS, it doesn't show rules inside media queries.

This is a good feature request, let me see how I can add support for this. Thanks for reporting!! 👍🏾

**Comment by phoenisx** [comment]
Thanks, for raising this issue, with all the details. 🙇🏾 

This is fixed in `v1.8.0`
