### ISSUE TITLE
Global custom properties no longer showing up

### ISSUE THREAD

**Issue by djmtype** [willofindie/vscode-cssvar#52]
I don't know if the update broke something. But, 2 days ago, this extension was working great. It was able to pick up all my css custom properties. Now, it doesn't seem to work. Only intellisense picks up on the custom properties I've used within the same file.

I tried re-enabling the extension and rechecking its settings.  I just added `"cssvar.files": ["**/*.css"]`, but it made no difference.

Here are my settings: 

```json
"cssvar.postcssPlugins": ["postcss-preset-env"],
	"cssvar.extensions": [
		"css",
		"scss",
		"sass",
		"less",
		"postcss",
		"vue",
		"svelte",
		"astro",
		"jsx"
	],
	"cssvar.postcssSyntax": [
		"@tokencss/postcss",
		"postcss-preset-env",
		"open-props"
	],
	"cssvar.files": ["**/*.css"],
```

It fails in .astro files without an alert. Within .css files, I get the screenshot attached: 
![Screen Shot 2022-07-28 at 2 18 04 PM](https://user-images.githubusercontent.com/930713/181609389-ab7f6ea4-c0f6-4dc0-b042-ad31df84e446.png)

**Comment by phoenisx** [comment]
It clearly looks like the parser is failing to parse the CSS file, which shouldn't be the case, as I released a safe-parser which should work for any type of file.

Can you help with the following details:
- Extension version you are using right now?
- Are you using [VSCode's multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces)?
- Provide VSCode logs. Please follow [this doc](https://github.com/willofindie/vscode-cssvar/blob/main/debug-extension.md) to provide log details.
  - I would need contents from the file which is failing to get parsed. The line number and file name details can be seen in the log.

Also, to understand your `cssvar` settings:
- [Supported CSS syntaxes](https://github.com/postcss/postcss#syntaxes) for `cssvar.postcssSyntax` are:
  - `postcss-scss` (for `scss`)
  - `postcss-sass` (for `sass`)
  - `postcss-less` (for `less`)

In your config, I am not sure what does `"@tokencss/postcss"` do. Is it a [supported postcss syntax parser](https://github.com/postcss/postcss#syntaxes).

**Comment by phoenisx** [comment]
You can also refer to the [examples](https://github.com/willofindie/vscode-cssvar/tree/main/examples), if your vscode settings are correctly set or not 👍🏾

**Comment by djmtype** [comment]
Thanks @phoenisx 

I have a bunch of errors like these: 
![Screen Shot 2022-07-28 at 4 48 39 PM](https://user-images.githubusercontent.com/930713/181636577-036e5e91-ed0d-4f1f-b612-63627badeee7.png)

Currently, it's now working but only within css files. However, between the `<style>` in .astro files it's only picking up currently existing custom properties via Intellisense. 

I did the obvious thing and restarted my computer. That made no difference. 
Using Workspaces or not made no difference. 
I removed the TokenCSS from cssvar settings – made no difference

**Comment by djmtype** [comment]
I tried on VS Codium too. No errors, but doesn't work with Astro files either.

**Comment by phoenisx** [comment]
Is this the project: https://github.com/djmtype/astro-xenon that fails to parse the `main.css` files??

Anyways, I need to raise a PR to update Open-Props docs, because there has been some recent changes that by default ignores scanning `node_modules` files.

Due to this you will have to provide:
```jsonc
{
  // Do not ignore node_modules, which is ignored by default
  "cssvar.ignore": []
}
```

You can refer to [this example](https://github.com/willofindie/vscode-cssvar/blob/main/examples/css-in-node-modules/.vscode/settings.json) for better understanding.

**Comment by djmtype** [comment]
@phoenisx That's the repo, but it's the open-props branch. https://github.com/djmtype/astro-xenon/tree/open-props

It's still not offering css variables suggestions. 
I also tried adding a Vue component to an Astro project and that didn't provided suggestions to Open-Props or my local css variables either. It seems to only provide suggestion among other css files.

**Comment by phoenisx** [comment]
Hi @djmtype 

What is the extension of the file where you are not seeing any intellisense?

Can you share a short video clip or a reproduction of the issue that you are facing?
This would help me understand your problem better

**Comment by djmtype** [comment]
@phoenisx CSS Vars currently isn't showing suggestions from local css files or node modules on any .astro file within a <style> tag. I'll gladly share a screencast clip. I'll get to it a bit later today.

**Comment by djmtype** [comment]
@phoenisx I figured out my issue – me, or my muscle memory. 
Without I realizing, I'm so use to typing `var` first. But CSS Var expects `--` from the start which so much better as it saves a lot of typing. 

In CSS files, it works either way by typing `var` or by typing `--`. Frameworks like Astro and Vue, within a `style` tag, it only works by typing `--` first. 

However, I wouldn't change a thing. I just need to train my brain.

**Comment by phoenisx** [comment]
I feel the issue is with using PostCSS plugin, as raised earlier https://github.com/willofindie/vscode-cssvar/issues/38#issuecomment-1161198828

**Comment by phoenisx** [comment]
Hi @djmtype 

Were u able to find details on the issue? Was any other extension causing conflict with this one?

Also, I wanted to know, Are you working on a local file system or a remote file system project?

**Comment by djmtype** [comment]
Hey @phoenisx  
Thanks again, it seems the [PostCSS Intellisense](https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-postcss) plugin was creating the conflict with CSS Vars enabled. 

I'm just working on a local project.
