### ISSUE TITLE
[Feat] ability to run linter in pre-commit / pre-push hook

### ISSUE THREAD

**Issue by jjenzz** [willofindie/vscode-cssvar#77]
in the absence of a build step that can fail if there are type errors, it would be useful to be able to run the linter in a pre-commit / pre-push hook that can block the commit / push when errors are found.

(this is not a super important feature tho, definitely a nice to have / low priority)

**Comment by jjenzz** [comment]
hmmm, i actually wonder if it isn't worth focusing efforts on the linter side of things because it has been brought to my attention that i could use stylelint for highlighting unknown variables instead, and it integrates well with CI.

**Comment by phoenisx** [comment]
To my knowledge, users usually use a library to add git hooks or integration some flows in CI pipelines.
This project is purely an extension and there's no node package for the same.

Not sure how you wanted to use this extension as a git hook or in the CI pipeline.


Do enlighten me if I am missing something here, where extensions can be used in CI pipelines?

**Comment by jjenzz** [comment]
> Do enlighten me if I am missing something here, where extensions can be used in CI pipelines?

ah sorry, i wasn't proposing the extension is used in CI pipelines because as you say, that's not possible, but also didn't want to propose a solution here in case you had good ideas for handling this that i hadn't considered.

my thinking was that the extension could read a configuration file that can also be read by a cli based linter (to avoid configuration in two separate places) but given our recent conversations and change of direction, i am going to close this :)
