### ISSUE TITLE
Support CSS `env` function

### ISSUE THREAD

**Issue by phoenisx** [willofindie/vscode-cssvar#8]
This is very new and not supported in browsers as of now.

Specification for this can be found here - https://drafts.csswg.org/css-env-1/

Though `PostCSS` plugins have started supporting this function. Check [postcss-env-function](https://github.com/csstools/postcss-env-function).

What I need to do is, support JS files, that will contain few variable exports, which should be added to `cssvar` intellisense.

**Comment by madeleineostoja** [comment]
For what it's worth I don't think this is really in the scope of css variable autocomplete, at least not until the spec has matured and is on path to be supported by browsers.

**Comment by phoenisx** [comment]
I am not planning to support it anytime soon 😅 .
I have just kept this issue open for my reference.

My first priority is to support https://github.com/willofindie/vscode-cssvar/issues/1, which requires a complete re-write of this plugin, and am not getting enough time to work on the same.

Anyways, thanks for your support @madeleineostoja 👍🏾

**Comment by phoenisx** [comment]
Deferring this task.
