### ISSUE TITLE
[Feat] Support CSS variables defined by TypeScript

### ISSUE THREAD

**Issue by penx** [willofindie/vscode-cssvar#98]
**Is your feature request related to a problem? Please describe.**

When using Chakra UI, and [calling the extendTheme function](https://chakra-ui.com/docs/styled-system/customize-theme):

```ts
import { extendTheme } from "@chakra-ui/react"

const colors = {
  admin: {
    dark: '#000',
  }
} as const

const theme = extendTheme({
  colors
});
```

CSS variables will be made available of the format `--chakra-colors-admin-dark`.

**Describe the solution you'd like**

If I could define a TypeScript type as follows:

```ts
type ColorVars = "--chakra-colors-admin-dark" | "--chakra-colors-admin-light" | "--chakra-colors-admin-rebeccapurple"
```

It would be great to be able to point vscode-cssvar at this type and have it pick up these variables to include them in autocomplete.

**Describe alternatives you've considered**

Somehow generate a css file from the typescript type or call to `extendTheme`.

**Additional context**

I may be able to help contribute this feature if you give me some pointers.

**Comment by phoenisx** [comment]
I think this: https://github.com/willofindie/vscode-cssvar/issues/92 is what you are trying to solve by creating a TS type.

JSON data is more informative compared to TS types and is widely known & used. I feel it would be good to use `.json` to define dynamically generated CSS custom props (If that's what you are looking for).😉 

If you want to contribute, you can check `src/main.ts#setup` and `src/parser.ts#parseFile` methods, where we need the changes, and conditionally handle parsing a CSS or JSON file. 👍🏽

**Comment by penx** [comment]
Thanks!

Loading from a JSON file means we would need a build step to create a JSON file when the `colors` object changes to keep up to date, and ideally to have this running in the background monitoring changes.

Loading from the TypeScript type means the CSS variables would come directly from the source code, not requiring a background task or build step.

I would prefer the TypeScript support, but yes I think #92 is solving the same problem.

Thanks for creating this library <3

**Comment by penx** [comment]
In case it helps, the type would come straight from the source code by using:


```ts
const colors = {
  admin: {
    dark: '#000',
    light: '#FFF',
    rebeccapurple: '#639'
  }
} as const

type Squashed<T> = keyof {
  [Property in keyof T as T[Property] extends string | number | boolean | null
    ? Property
    : `${string & Property}-${string & Squashed<T[Property]>}`]: true;
};
type Vars<T> = keyof {
  [Property in keyof T as T[Property] extends string | number | boolean | null
    ? Property
    : `--chakra-colors-${string & Property}-${string & Squashed<T[Property]>}`]: true;
};

type ColorVars = Vars<typeof colors>
```
[Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBKA2IBOEYF4YG8BQMYEMATAWwEswAuLXPGQ-JAayoHIBiABi5YBoa94pAOYALKKzYAxab34wkAUwBGC4MHwAHAK5IN8BRIBsAZgCcLGgF9slgqlCQo2bFACeGhTADKARy34IEQVCAB4AFQA+dBhGBVcQADNqPABtAAUkEA8kNxhyGLjEmDC7YvTM7LcAXRgFAA8oBTBCVGgkciEYAB8YMC1iFSRumCUQEH18MGG++Hg5AH4YDKyFHNc5KgADABJMNo6YADIlitW3SwBaXf2wTuPff0Dg8PKVtaqIy02qqigkLQUAG4bMC3B4YAA1BgQcJRDCxeJJHCpZaVVx5KYIoolAJlVFnVw1eqNZqtP4HHp9AarYajcYKSbTLSzBYnN5uDYwTYXC7AET4RhIfC88bICBXPbk25HNloy7XKV3bx+AJBUJhV5oj5fH4wP4A4GWYEudyeADCoqQUJQ0WtMLBCiKCDFEWwQA)

**Comment by penx** [comment]
I was thinking that, given a a path to certain file, a vscode extension could connect to the TS language server and load the types from that file.

I thought there was something in the vscode API to do this, but I can't find it, nor can I find any documentation to help.

Please let me know if you've seen anything :)

**Comment by phoenisx** [comment]
If you want typing support, isn't Typescript already providing that for the dynamic CSS variables created by Chakra?

Can u help me understand what you are looking for with an example?

**Comment by phoenisx** [comment]
@penx I think what you are talking about is not Typing support for the CSS variable, but instead, IntelliSense (auto-completion) support, that this extension provides.

This extension requires at least a key-value pair ([key]: CSS variable name, and [value]: CSS variables value) to provide CSS variable IntelliSense.
I was

**Comment by penx** [comment]
> I think what you are talking about is not Typing support for the CSS variable, but instead, IntelliSense (auto-completion) support, that this extension provides

Originally yes, but I have since realised I can create a typed helper `cssvar["colors-dark"]` that autocompletes and is checked by TS.

> This extension requires at least a key-value pair ([key]: CSS variable name, and [value]: CSS variables value

My thinking was that the value wouldn't be known, and the extension would set this to null/empty string for TypeScript defined CSS variables. But yes, a JSON file containing your themes and their respective values would be a better experience.

Feel free to close this issue! There may be a benefit to people defining their CSS variables in TypeScript and consuming them in CSS files, but that doesn't apply to us :)

**Comment by penx** [comment]
Our ts-only solution is as follows, in case anyone ends up here looking for something similar :)

```ts
import type { Theme } from "@chakra-ui/theme";
import { extendTheme } from "@chakra-ui/react";

const themeExtension = {
  colors: {
    dark: '#111',
    light: '#EEE',
  }
} as const;

export const theme = extendTheme(themeExtension);

export type CustomTheme = typeof adminTheme & Theme;

type ThemeObject = {
  [key: string]: number | string | ThemeObject;
};

type Squashed<T extends ThemeObject> = keyof {
  [Property in keyof T as T[Property] extends ThemeObject
    ? `${string & Property}-${string & Squashed<T[Property]>}`
    : Property]: true;
};

const tokens = [
  "colors",
  // "borders",
  // "fonts", etc.
] as const;

type Tokens = Squashed<Pick< CustomTheme, typeof tokens[number]>>;

export type CSSVars = {
  [K in Tokens]: `--chakra-${K}`;
};

export const cssvar = new Proxy<CSSVars>({} as CSSVars, {
  get(_, id: string) {
    return `var(--chakra-${id})`;
  },
});

export { theme };
```


Usage:
```ts
const MyComponent = styled("div")({
  color: cssvar["colors-dark"],
});
```

**Comment by phoenisx** [comment]
@penx Thanks for the detailed explanation.

I will close this issue and track support for dynamic variables in #92
