### ISSUE TITLE
[Bug] Can't set pcss as extension

### ISSUE THREAD

**Issue by equinusocio** [willofindie/vscode-cssvar#99]
**Describe the bug**
Whle https://github.com/willofindie/vscode-cssvar/issues/15 seems to be fixed, I'm not able to assign `pcss` to the config array, even is is a perfect valid postcss extension suggested for any postcss file since enables vscode completation, stylelint validations and postcss plugin support.

**To Reproduce**
1. Add this to vscode config
```json
  "cssvar.extensions": [
    "css", "pcss", "jsx", "tsx"
  ],
```

**Expected behavior**
No warning about `pcss` extensions

**Screenshots**
![CleanShot 2022-11-28 at 18 12 00](https://user-images.githubusercontent.com/10454741/204339578-64408a31-93a4-4219-8bf1-2af09c629f5b.png)

**Additional Info**

Some of the accepted values are not extensions at all, like `postcss` and `stylus` are not file extensions, they are language IDs and their relative extensions are `.pcss` and `.styl`. Language IDs and file extensions are two completely different things in vscode.

>**Warning**
By adding `postcss` to the list it works for all files using `postcss` id, indipendently from their extension. It looks like a mispelled setting name since seems to work with languages and not file extensions

**Solution**

Rename `cssvar.extensions` into `cssvar.languages` or make it work with file extensions and not language IDs.

**Comment by phoenisx** [comment]
Agreed!!

The config name was chosen initially to point only extension names, but the code has changed a lot and for backwards compatibility I never renamed it.

I will take a look into this once I am back.
If you want to work on it please feel free to open a PR.☺️

Thanks for raising this concern 👍
